spring.application.name=ecommerce
server.port=8080

# ================== DATABASE (SUPABASE CHO RENDER & LOCAL) ==================
# Lấy chính xác host và port từ Supabase, nhớ thêm ?sslmode=require ở cuối
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require

# Lấy chính xác user từ Supabase
spring.datasource.username=postgres.jabolkibwkhmyeemliwl

# Vẫn giữ nguyên biến môi trường để bảo mật
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ================== CÁC CẤU HÌNH KHÁC (GIỮ NGUYÊN) ==================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

spring.web.cors.allowed-origins=*

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=victornguyen19072004@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=4c36e651f42157b9ac25ade5303fd36c
